@startuml "Demo Generated"
    !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
    LAYOUT_WITH_LEGEND()
    AddRelTag("async",  $lineStyle = DottedLine())
    AddElementTag("acl",  $bgColor = "#6F9355")
    Boundary(project, "Our system"){
  Container(bff, "bff")
Container(camunda, "camunda")
Container(goods_acl, "goods acl", "", "", $tags="acl")
Container(invoice_acl, "invoice acl", "", "", $tags="acl")
Container(invoice_repository, "invoice repository")
ContainerDb(invoice_repository_db, "DB")
Rel(invoice_repository, invoice_repository_db, "")
            Container(stock_acl, "stock acl", "", "", $tags="acl")
Container(task_repository, "task repository")
ContainerDb(task_repository_db, "DB")
Rel(task_repository, task_repository_db, "")
            }
Rel(bff, invoice_repository, "")
            Rel(bff, task_repository, "")
            Rel(bff, camunda, "")
            Rel(bff, goods_acl, "")
            Rel(camunda, invoice_repository, "")
            Rel(camunda, task_repository, "")
            Rel(camunda, stock_acl, "")
            Rel(camunda, invoice_acl, "")
            System_Ext(goods_repository, "goods_repository", " ")
Rel(goods_acl, goods_repository, "", "https://gateway.int.com:443/goods/v1")
            System_Ext(goods2_repository, "goods2_repository", " ")
Rel(goods_acl, goods2_repository, "", "https://gateway.int.com:443/goods2/v1")
            System_Ext(ext_system, "ext_system", " ")
Rel(invoice_acl, ext_system, "", "https://gateway.int.com:443/ext/v1")
            System_Ext(invoice_input, "invoice_input", " ")
Rel(invoice_acl, invoice_input, "", "orig-invoice-q8s-v1", $tags="async")
            System_Ext(invoice_output, "invoice_output", " ")
Rel(invoice_acl, invoice_output, "", "result-invoice-q8s-v1", $tags="async")
            System_Ext(stock, "stock", " ")
Rel(stock_acl, stock, "", "https://gateway.int.com:443/stock/v1")
            @enduml